---
EnableDefaultLinters: true
exclude:
  - "vendor/bundle/**/*"
linters:
  ErbSafety:
    enabled: true
  FinalNewline:
    enabled: true
  PartialInstanceVariable:
    enabled: true
  DeprecatedClasses:
    enabled: true
  HardCodedString:
    enabled: true
    exclude:
      - "app/views/dashboard/show.html.erb"
      - "app/views/public/landing_page.html.erb"
